name: payment-api

on:
  workflow_dispatch:

env:
  SERVICE: payment-api
  IMAGE: payment.api

jobs:
  Call-dev-sec-ci:
    uses: ./.github/workflows/dev-sec-ci.yml
    with:
      imageName: payment-api
      projectPath: src/Services/Payment/Payment.API
      projectName: Payment.API.csproj
    secrets:
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      AZ_APPINSIGHTS_CONNECTION_STRING: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}  
      AZ_SUBSCRIPTION_TOKEN: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}

  deploy-to-kubernetes:     
    needs: Call-dev-sec-ci
    uses: ./.github/workflows/deploy-container-cd.yml    
    with:      
      kustomize-input-directory: deploy/k8s/kustomize/services/payment
      kustomize-output-file: deploy/k8s/kustomize/services/payment/payment-api.output.yml
      imageName: payment-api
    secrets:      
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AKS_NAME: ${{ secrets.AKS_NAME }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}                         